version: "3.7"

services:
  meshtastic-node:
    build: .
    networks:
      - mesh
    ports:
      - 4403:4403
    volumes:
      - portduino_app:/home/mesh
networks:
  mesh:

volumes:
  portduino_app: